apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcon-ingress
  namespace: staging
spec:
  rules:
  - host: falcon.tonguru.com
    http:
      paths:
      - backend:
          serviceName: falcon-webapp-service
          servicePort: 80
  
  - host: tomcat.falcon.tonguru.com
    http:
      paths:
      - backend:
          serviceName: tomcat
          servicePort: 8080
    
  - host: phpmyadmin.falcon.tonguru.com
    http:
      paths:
      - backend:
          serviceName: phpmyadmin
          servicePort: 80
