apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: falcon-ingress
  namespace: staging
spec:
  rules:
  - host: falcon.tonguru.com
    http:
      paths:
      - backend:
          service:
            name: falcon-webapp-service
            port: 80
